services:
  postgres:
    image: postgres:15
    container_name: mock-shelf-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mock-shelf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./src/test/resources/docker/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  activemq:
    image: apache/activemq-artemis:2.40.0
    container_name: mock-shelf-activemq
    ports:
      - "61616:61616"  # JMS
      - "8161:8161"    # Web console
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8161"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: mock-shelf-keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: dev-file
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8081:8080"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./src/test/resources/docker/keycloak/spring-realm.json:/opt/keycloak/data/import/spring-realm.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 5s
      timeout: 10s
      retries: 3

  wiremock:
    image: wiremock/wiremock:2.35.0
    container_name: mock-shelf-wiremock
    ports:
      - "8082:8080"
    volumes:
      - ./src/test/resources/mappings:/home/wiremock/mappings
      - ./src/test/resources/__files:/home/wiremock/__files
    command:
      - --verbose
      - --global-response-templating
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/"]
      interval: 10s
      timeout: 5s
      retries: 3

  maildev:
    image: maildev/maildev:2.0.5
    container_name: mock-shelf-maildev
    ports:
      - "1025:1025"  # SMTP port
      - "10080:1080"  # Web interface
    environment:
      MAILDEV_INCOMING_USER: maildev
      MAILDEV_INCOMING_PASS: maildev
