spring:
  application:
    name: mock-shelf
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/mock-shelf}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/spring

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

  # ActiveMQ configuration
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:vm://embedded?broker.persistent=false}
    user: ${ACTIVEMQ_USER:admin}
    password: ${ACTIVEMQ_PASSWORD:admin}
    packages:
      trust-all: true

    # Email configuration
  mail:
    host: ${MAIL_HOST:smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:username}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# MockShelf application settings
mock-shelf:
  email:
    from: noreply@mockshelf.com
    name: MockShelf Library
  queue:
    notifications: mockshelf.notifications
  isbn:
    api:
      url: https://openlibrary.org/api/books?bibkeys=ISBN:{isbn}&format=json&jscmd=data
      timeout: 5000
  loan:
    reminder-days-before-due: 7
  app:
    url: ${APP_URL:http://localhost:8080}


org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true
