spring:
  application:
    name: mock-shelf
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/mock-shelf}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:mock-shelf}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:sK5v1zhHV7EkP5YhCcrnBvUxBsmrnDCo}
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/spring}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/auth/realms/spring}

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

  # ActiveMQ configuration
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    user: ${ACTIVEMQ_USER:artemis}
    password: ${ACTIVEMQ_PASSWORD:artemis}

  # Email configuration
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:maildev}
    password: ${MAIL_PASSWORD:maildev}


# MockShelf application settings
mock-shelf:
  email:
    from: noreply@mockshelf.com
    name: MockShelf Library
  queue:
    notifications: mockshelf.notifications
  isbn:
    api:
      url: https://openlibrary.org/api/books?bibkeys=ISBN:{isbn}&format=json&jscmd=data
      timeout: 5000
  loan:
    reminder-days-before-due: 7
  app:
    url: ${APP_URL:http://localhost:8080}

org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true
